import testimonials from "./testimonials"
import abouts   from "./abouts"
import contact from "./contact"
import experiences from "./experiences"
import frontEndSkills from "./frontEndSkills"
import backendSkills from "./backendSkills"
import devopsSkills from "./devopsSkills"
import workExperience from "./workExperience"
import works from "./works"
export const schemaTypes = [testimonials,abouts,contact,workExperience,experiences,frontEndSkills,devopsSkills,backendSkills,works]
